const tags = [
  [
    'Drawing Style',
    [
      'Cel Shading',
      'Crosshatch',
      'Detailed and Intricate',
      'Doodle',
      'Dot Art',
      'Line Art',
      'Sketch',
      "Children's Drawing"
    ]
  ],
  [
    'Visual Style',
    [
      '16-bit',
      '2D',
      '8-bit',
      'Anaglyph',
      'Anime',
      'Art Nouveau',
      'Baroque',
      'Bauhaus',
      'Brutalist',
      'Cartoon',
      'CGI',
      'Comic Book',
      'Concept Art',
      'Constructivist',
      'Cubist',
      'Dadaist',
      'Digital Art',
      'Dystopian',
      'Expressionist',
      'Fantasy',
      'Fauvist',
      'Figurative',
      'Geometric',
      'Graphic Novel',
      'Hard Edge Painting',
      'Hydrodipped',
      'Impressionistic',
      'Liminal space',
      'Lithography',
      'Manga',
      'Minimalist',
      'Modern Art',
      'Mosaic',
      'Mural',
      'Naive',
      'Neoclassical',
      'Photo',
      'Realistic',
      'Rococo',
      'Romantic',
      'Splatter Art',
      'Street Art',
      'Stuckist',
      'Surrealist',
      'Symbolist',
      'Ukiyo-e',
      'Visual Novel',
      'Watercolor'
    ]
  ],
  [
    'Time Periods',
    [
      '1700s',
      '1800s',
      '1900s',
      '1910s',
      '1920s',
      'Roaring 20s',
      '1930s',
      '1940s',
      '1950s',
      '1960s',
      '1970s',
      '1980s',
      '1990s',
      '2000s',
      '2010s',
      'Elizabethan',
      'Medieval',
      'Prehistoric',
      'Preraphaelite',
      'Victorian'
    ]
  ],
  [
    'Aesthetics and Punks',
    [
      '1950s Suburbia',
      'Acidwave',
      'Aetherpunk',
      'Afropunk',
      'Americana',
      'Apocalyptic',
      'Arcade',
      'Art Deco',
      'Atompunk',
      'Avant-Garde',
      'Baroque',
      'Bauhaus',
      'Black Metal',
      'Bohemian',
      'Bronzepunk',
      'Brutalist',
      'Bubblegum',
      'Cassette Futurism',
      'Celtic',
      'Chic Modernist',
      'Chunyu',
      'Clockpunk',
      'Cogpunk',
      'Color Pop',
      'Corporate Grunge',
      'Cottagecore',
      'Country Aesthetic',
      'Cybergoth',
      'Cyberpop',
      'Cyberprep',
      'Cyberpunk',
      'Dark Fantasy',
      'Dark Gatsby',
      'Dia De Los Muertos, La Catrina',
      'Dieselpunk',
      'Disco',
      'Downtown style',
      'Dreamy',
      'Edgy',
      'Emo Goth',
      'Emo',
      'Europunk',
      'Fairytale',
      'Fantasy',
      'Film Noir',
      'Folk Punk',
      'Foodie',
      'Frutiger Aero',
      'Frutiger Aurora',
      'Frutiger Eco',
      'Frutiger Metro',
      'Furry',
      'Gangsta',
      'Gearpunk',
      'Girl-Next-Door',
      'Glam',
      'Glamorous',
      'Gloomcore',
      'Gloomy',
      'Goth Punk',
      'Goth',
      'Gothic',
      'Greaser',
      'Grotesque',
      'Grunge',
      'Hair Metal',
      'Harajuku Fashion',
      'Haute',
      'HipHop',
      'Hippie',
      'Hipster',
      'Holosexual',
      'Honeycore',
      'Icepunk',
      'Imaginarium',
      'Imperial Romanov',
      'Indie',
      'Juggalo',
      'Kawaii',
      'Kawaii Gamer',
      'Kitschy',
      'Lo-Fi',
      'Low-Poly',
      'Lunarpunk',
      'MS Paint',
      'Mad Scientist',
      'Magical Girl',
      'Maximalism',
      'Metal',
      'Metrosexual',
      'Mid-Century Modern',
      'Midwest Gothic',
      'Minimalism',
      'Modernist',
      'Nanopunk',
      'Nautical Fantasy',
      'Nautical',
      'Neo Baroque',
      'Neoclassicism',
      'New Age',
      'New England Gothic',
      'New Money',
      'New Wave',
      'Oceanpunk',
      'Old Hollywood',
      'Old Money',
      'Otaku',
      'Pastel Gore',
      'Pastel Goth',
      'Pastel Punk',
      'Pearly',
      'Pink Princess',
      'Pirate',
      'Pixelated',
      'Pixiecore',
      'Pop Art',
      'Post-Apocalyptic',
      'Preppy',
      'Psychedelic',
      'Punk',
      'Rainbowcore',
      'Retro',
      'Retro-Futuristic',
      'Rock and Roll',
      'Rock',
      'Rockabilly',
      'Rocketpunk',
      'Romanticism',
      'Sanrio style',
      'Sci-Fi',
      'Scrapbook Style',
      'Skeuomorphism',
      'Solarpunk',
      'Southern Gothic',
      'Soviet Brutalism',
      'Soviet Nostalgia',
      'Space Cowboy',
      'Steampunk',
      'Steelpunk',
      'Stonepunk',
      'Stoner',
      'Surrealism',
      'Tiki',
      'Tropical',
      'Uotown Aesthetic',
      'Vaporwave',
      'Vintage Americana',
      'Vintage British Sportsman',
      'Vintage Hero',
      'Visual Kei',
      'Web 1.0',
      'Web 2.0',
      'Weeaboo',
      'Weirdcore',
      'Witchy Academia',
      'Y2K',
      'Yakuza',
      'Yandere',
      'Yankee',
      'Zombie Apocalypse'
    ]
  ],
  [
    'Pen',
    ['Chalk', 'Colored Pencil', 'Crayon', 'Graphite', 'Ink', 'Oil Paint', 'Pastel Art']
  ],
  [
    'Carving and Etching',
    [
      'Etching',
      'Linocut',
      'Paper Model',
      'Paper-Mache',
      'Papercutting',
      'Pyrography',
      'Wood-Carving'
    ]
  ],
  [
    'Camera',
    [
      '18mm',
      '35mm',
      '70mm',
      '85mm',
      '100mm',
      '150mm',
      'Aerial View',
      'Amateur Photography',
      'Bokeh',
      'Canon50',
      'Cinematic',
      'Cinematic Postprocessing',
      'Close-up',
      'Color Grading',
      'Depth of Field',
      'Disposable Camera',
      'DOF',
      'Dramatic',
      'DSLR Photo',
      'Ektachrome',
      'F1.8',
      'F11',
      'Film Grain',
      'Film Still',
      'Fisheye Lens',
      'Field of View',
      'FOV',
      'Glamor Shot',
      'Golden Hour',
      'HD',
      'High Angle',
      'IMAX',
      'iso3200',
      'Kodachrome',
      'Landscape',
      'Lens Flare',
      'Low Angle',
      'Macro',
      'Moire',
      'Natural Lighting',
      'Nikon D800',
      'Photoshoot',
      'Polaroid',
      'Portrait',
      'QHD',
      'RAW Photo',
      'Studio Lighting',
      'UHD',
      'VHS',
      'Vignette',
      'Vintage',
      'War Photography',
      'White Balance',
      'Wide Angle',
      'Wildlife Photography'
    ]
  ],
  [
    'Color',
    [
      'Beautiful Lighting',
      'Cold Color Palette',
      'Colorful',
      'Dynamic Lighting',
      'Electric Colors',
      'Infrared',
      'Neon',
      'Pastel',
      'Synthwave',
      'Volumetric Lighting',
      'Warm Color Palette'
    ]
  ],
  [
    'Emotions',
    [
      'Angry',
      'Bitter',
      'Disgusted',
      'Embarrassed',
      'Evil',
      'Excited',
      'Fear',
      'Funny',
      'Happy',
      'Horrifying',
      'Lonely',
      'Sad',
      'Serene',
      'Surprised',
      'Melancholic'
    ]
  ],
  [
    'Artists and communities',
    [
      '500px',
      'trending on 500px',
      'Artstation',
      'trending on Artstation',
      'Behance',
      'trending on Behance',
      'CGSociety',
      'by Agnes Lawrence Pelton',
      'by Akihito Yoshida',
      'by Alex Grey',
      'by Alexander Jansson',
      'by Alphonse Mucha',
      'by Andre Kohn',
      'by Andy Warhol',
      'by Ansel Adams',
      'by Artgerm',
      'by Asaf Hanuka',
      'by Aubrey Beardsley',
      'by Banksy',
      'by Beeple',
      'by Ben Enwonwu',
      'by Bob Eggleton',
      'by Caravaggio Michelangelo Merisi',
      'by Caspar David Friedrich',
      'by Chris Foss',
      'by Chihuly',
      'by Claude Monet',
      'by Craig Mullins',
      'by Dan Mumford',
      'by Darek Zabrocki',
      'by David Mann',
      'by Diego Velázquez',
      'by Disney Animation Studios',
      'by Édouard Manet',
      'by Esao Andrews',
      'by Frida Kahlo',
      'by Gediminas Pranckevicius',
      `by Georgia O'Keeffe`,
      'by Greg Hildebrandt',
      'by Greg Rutkowski',
      'by Gustave Doré',
      'by Gustave Klimt',
      'by H.R. Giger',
      'by Hayao Miyazaki',
      'by Henri Matisse',
      'by HP Lovecraft',
      'by Ilya Kuvshinov',
      'by Ivan Shishkin',
      'by Jack Kirby',
      'by Jackson Pollock',
      'by James Jean',
      'by Jean-Michel Basquiat',
      'by Jim Burns',
      'by Johannes Vermeer',
      'by John William Waterhouse',
      'by Katsushika Hokusai',
      'by Kim Tschang Yeul',
      'by Ko Young Hoon',
      'by Leng Jun',
      'by Leonardo da Vinci',
      'by Lisa Frank',
      'by Luis Royo',
      'by M.C. Escher',
      'by Magali Villeneuve',
      'by Mahmoud Saïd',
      'by Makoto Shinkai',
      'by Marc Simonetti',
      'by Mark Brooks',
      'by Michelangelo',
      'by Naoto Hattori',
      'by Pablo Picasso',
      'by Paul Klee',
      'by Patrice Murciano',
      'by Peter Mohrbacher',
      'by Pierre-Auguste Renoir',
      'by Pixar Animation Studios',
      'by Rembrandt',
      'by Richard Dadd',
      'by Rossdraws',
      'by Salvador Dalí',
      'by Sam Does Arts',
      'by Sandro Botticelli',
      'by Shaun Tan',
      'by Slava Semenyuta',
      'by Slava Thisset',
      'by Ted Nasmith',
      'by Ten Hundred',
      'by Thomas Kinkade',
      'by Tivadar Csontváry Kosztka',
      'by Victo Ngai',
      'by Vincent Di Fate',
      'by Vincent van Gogh',
      'by Wes Anderson',
      'by William Eggleston',
      'by WLOP',
      'by Yoshitaka Amano',
      'by Zdzisław Beksiński',
      'DeviantArt',
      'trending on DeviantArt',
      'Dribbble',
      'trending on Dribbble',
      'Pixiv',
      'trending on Pixiv'
    ]
  ],
  [
    'CGI Software',
    [
      '3D Model',
      '3D Sculpt',
      '3Ds Max Model',
      'Blender Model',
      'Cinema4d Model',
      'Maya Model',
      'Unreal Engine',
      'Zbrush Sculpt'
    ]
  ],
  [
    'CGI Rendering',
    [
      '3D Render',
      'Corona Render',
      'Creature Design',
      'Cycles Render',
      'Detailed Render',
      'Environment Design',
      'Glass Caustics',
      'Global Illumination',
      'Intricate Environment',
      'LSD Render',
      'Octane Render',
      'PBR',
      'Subsurface Scattering'
    ]
  ]
]

export default tags
